Repository opnsense/docs, pull requests merged in 2025-01, with the labels that each got.

#651 vpn/ipsec: Add additional information to swanctl roadwarrior docs
  source/manual/how-tos/ipsec-swanctl-rw-ikev2-eap-mschapv2.rst
Labels: cleanup, feature

#656 Clarify WireGuard Road Warrior Setup doc
  source/manual/how-tos/wireguard-client.rst
Labels: cleanup

#660 Update settingsmenu.rst for new sshd_config overrides
  source/manual/settingsmenu.rst
Labels: feature

#664 Fixed typo: gatew -> gateway
  source/manual/multiwan.rst
Labels: cleanup

#655 vpn/openvpn: Add note about static-challenge option in sslvpn_client.rst
  source/manual/how-tos/sslvpn_client.rst
Labels: cleanup

#657 firewall/nat: Explain filter rule association in nat.rst
  source/manual/nat.rst
Labels: cleanup
